### ISSUE TITLE
Port expose

### ISSUE THREAD

**Issue by brunowego** [langri-sha/npm_lazy#1]
Will be nicer if expose a port :+1:

**Comment by langri-sha** [comment]
Thanks @brunobatista. I'll make sure to expose the port to better document the `npm_lazy` server defaults.

**Comment by brunowego** [comment]
Thanks @langri-sha :+1:

**Comment by brunowego** [comment]
Another thing you can add in the documentation is the run command, like:

``` bash
docker run --name npm-lazy -p 8080:8080 -d langrisha/npm-lazy
```

It will help another users to use your container.

**Comment by langri-sha** [comment]
A proper README for those that haven't used mixu/npm_lazy before is definitely lacking. I'm on top of it!

**Comment by brunowego** [comment]
:+1:
