### ISSUE TITLE
Use environment to control program arguments

### ISSUE THREAD

**Issue by StanAngeloff** [langri-sha/npm_lazy#16]
I pushed a [commit](https://github.com/StanAngeloff/npm_lazy/commit/174bf2a429e900fd3b875155d7c825a2fd0b72fb) earlier today that allows the use of environment variables.

I thought you may be interested in cherry-picking if you found it useful?

``` sh
export NPM_LAZY_PORT=80
export NPM_LAZY_EXTERNAL_URL=http://localhost
node index.js
```

**Comment by langri-sha** [comment]
This looks great! Could you please open a PR?
