### ISSUE TITLE
How change address

### ISSUE THREAD

**Issue by brunowego** [langri-sha/npm_lazy#2]
I have been changed the external URL but when install dependencies I get this message:

Terminal output:

``` bash
npm ERR! fetch failed http://localhost:8080/assemble/-/assemble-0.4.42.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed http://localhost:8080/assemble/-/assemble-0.4.42.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
```

My external URL:

```
externalUrl: 'http://10.200.1.128:8081',
```

Any idea how fix it? Thanks!

**Comment by langri-sha** [comment]
I you ran `docker exec` and can see that the `config.js` module your loading has indeed changed in the container, but the server still uses the default configuration, then it might be some unexpected behavior related to how docker manages `CMD/ENTRYPOINT/COPY/ADD/VOLUME` and the passed container options.

It is just an assumption, but it might well be that the container started the server before your changes have been written and committed to the container's filesystem. I'll allocate some time in the morning and see if I can reproduce just what your experiencing and update the README accordingly.

**Comment by langri-sha** [comment]
Hi @brunobatista! I revamped the container, with support for configuring `npm_lazy` with run commands. I'll close the issue, but please give it a go and re-open it if you still have any difficulties with running a custom server.
